#!/bin/sh

echo "This will take some time."

apt-get update
apt-get upgrade
apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++ git libgmp-dev

git clone https://github.com/magi-project/m-cpuminer-v2.git

cd m-cpuminer-v2

./autogen.sh
./configure CFLAGS="-O3" CXXFLAGS="-O3"
make

echo "Installed. Usage is ./m-minerd while inside the 'm-cpuminer-v2' folder."
